from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(User)
admin.site.register(EmployeeDetail)
admin.site.register(EmailOTP)
admin.site.register(LoginHistory)
admin.site.register(Attendance)
admin.site.register(Leave)
admin.site.register(Holiday)
admin.site.register(BankDetail)
admin.site.register(SalaryComponent)
admin.site.register(SalaryHistory)
admin.site.register(QR_Session)
admin.site.register(Project)
admin.site.register(ProjectMembers)
admin.site.register(Task)
admin.site.register(ProjectImages)
admin.site.register(ProjectFile)
admin.site.register(Department)
admin.site.register(Designation)
admin.site.register(Branch)
admin.site.register(ShiftTable)
admin.site.register(Shiftaddon)
admin.site.register(NotificationLog)
admin.site.register(TermsAndConditions)
admin.site.register(PrivacyPolicy)
admin.site.register(AboutUs)
admin.site.register(Notice)
admin.site.register(Worksheet)
admin.site.register(TrainingVideo)
admin.site.register(Form)
admin.site.register(Question)
admin.site.register(QuestionOption)
admin.site.register(EmployeeGoogleFormResponse)
