# Generated by Django 5.2.7 on 2025-11-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegoogleformresponse',
            name='adhar_card',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeegoogleformresponse',
            name='bank_passbook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeegoogleformresponse',
            name='pan_card',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeegoogleformresponse',
            name='passport_size_photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeegoogleformresponse',
            name='qualification_documents',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeegoogleformresponse',
            name='resume',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
