# Generated by Django 5.2.7 on 2025-11-26 05:00

import core_app.utils.encrypt_decrypt_data
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_employeegoogleformresponse_adhar_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('department', core_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=150)),
                ('description', core_app.utils.encrypt_decrypt_data.EncryptedTextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=255)),
                ('description', core_app.utils.encrypt_decrypt_data.EncryptedTextField(blank=True)),
                ('video_file', models.FileField(upload_to='training_videos/')),
                ('duration', core_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=755)),
                ('file', models.FileField(upload_to='worksheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', core_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=500, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
