# Generated by Django 5.2.5 on 2025-08-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_emailotp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='reporting_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
