# Generated by Django 5.2.6 on 2025-09-24 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_employeedetail_reporting_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='DEFAULT_CODE', max_length=255)),
                ('latitudes', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='qrsession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.qr_session'),
        ),
    ]
