# Generated by Django 5.2.7 on 2025-12-01 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_shifttable_break_end_shifttable_break_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('rate_type', models.CharField(max_length=20)),
                ('rate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_contribution', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_contribution', models.CharField(blank=True, max_length=255, null=True)),
                ('example_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shifttable',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='shifttable',
            name='break_start',
        ),
        migrations.RemoveField(
            model_name='shifttable',
            name='evening_break_end',
        ),
        migrations.RemoveField(
            model_name='shifttable',
            name='evening_break_start',
        ),
        migrations.RemoveField(
            model_name='shifttable',
            name='lunch_end',
        ),
        migrations.RemoveField(
            model_name='shifttable',
            name='lunch_start',
        ),
        migrations.RemoveField(
            model_name='shifttable',
            name='relaxation_end',
        ),
        migrations.RemoveField(
            model_name='shifttable',
            name='relaxation_start',
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core_app.salarycomponent'),
        ),
    ]
