# Generated by Django 5.2.6 on 2025-09-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_qr_session_attendance_qrsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_in',
            field=models.BooleanField(default=False),
        ),
    ]
