# Generated by Django 5.2.6 on 2025-09-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_attendance_punch_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_session',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qr_session',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
