# Generated by Django 5.2.7 on 2025-12-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_salarycomponent_remove_shifttable_break_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punchout_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
