# Generated by Django 5.2.6 on 2025-09-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_qr_session_expires_at_qr_session_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
