# Generated by Django 5.2.7 on 2025-12-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_attendance_punchout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttable',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttable',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttable',
            name='evening_break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttable',
            name='evening_break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttable',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttable',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttable',
            name='relaxation_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttable',
            name='relaxation_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
