# Generated by Django 5.2.7 on 2025-12-03 05:19

import core_app.utils.encrypt_decrypt_data
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_shifttable_break_end_shifttable_break_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='basic_earnings',
            field=core_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='employee_state_inssurance',
            field=core_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='income_tax',
            field=core_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='pf_deduction',
            field=core_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='proffessional_tax',
            field=core_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=120, null=True),
        ),
    ]
