# Generated by Django 5.2.7 on 2025-12-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_employeedetail_basic_earnings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='employee_state_inssurance',
            new_name='employee_state_insurance',
        ),
    ]
