# Generated by Django 5.2.6 on 2025-09-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_alter_leave_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_logo', models.FileField(upload_to='project_logo/')),
                ('project_name', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.CharField(verbose_name=100)),
                ('project_value', models.CharField(blank=True, null=True, verbose_name=100)),
                ('total_working_hours', models.CharField(max_length=50)),
                ('extra_time', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField()),
                ('attachment', models.FileField(upload_to='Project_attachment/')),
            ],
        ),
    ]
