# Generated by Django 5.2.7 on 2025-12-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_rename_employee_state_inssurance_employeedetail_employee_state_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
