# Generated by Django 5.2.7 on 2025-12-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_alter_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
