# Generated by Django 5.2.5 on 2025-09-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_task_project_projectmembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembers',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
