# Generated by Django 5.2.5 on 2025-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_alter_projectmembers_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
