# Generated by Django 5.2.7 on 2025-12-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_attendance_shifts_shiftaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttable',
            name='punch_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
