# Generated by Django 5.2.5 on 2025-09-27 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_leave_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='requested_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
