# Generated by Django 5.2.7 on 2025-12-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_shifttable_punch_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shifttable',
            name='start_time',
        ),
    ]
