# Generated by Django 5.2.6 on 2025-09-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
