# Generated by Django 5.2.7 on 2025-10-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_project_reason_for_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
