# Generated by Django 5.2.7 on 2025-10-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_employeedetail_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='emp_exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='emp_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
