# Generated by Django 5.2.7 on 2025-10-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0022_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
