# Generated by Django 5.2.7 on 2025-10-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0024_notificationlog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='action',
            field=models.CharField(max_length=500),
        ),
    ]
