# Generated by Django 5.2.7 on 2025-10-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0025_alter_notificationlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
