# Generated by Django 5.2.7 on 2025-10-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0026_leave_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
