# Generated by Django 5.2.7 on 2025-10-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0030_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
