# Generated by Django 5.2.7 on 2025-10-08 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0032_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
