# Generated by Django 5.2.7 on 2025-10-09 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0034_projectfile_projectimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.branch'),
        ),
    ]
