# Generated by Django 5.2.7 on 2025-10-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0035_employeedetail_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='selfie',
        ),
        migrations.AddField(
            model_name='attendance',
            name='in_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/in'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='out_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/out/'),
        ),
    ]
